pizzas/urls.py
"""Defines URL patterns for pizzeria"""
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # List of pizzas
    path('pizzas', views.pizzas, name='pizzas'),
    # Content of the pizza
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza_toppings'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pizzas/', include('pizzas.urls', namespace='pizzas')),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    """Names of pizzas"""
    name = models.CharField(max_length=200)
    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """Names of toppings for pizzas"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        """Return a string representation of the model."""
        return self.name        

pizzas/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import Pizza

def index(request):
    """The home page for pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas"""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    "Shows a pizza and its toppings"
    pizza = get_object_or_404(Pizza, id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

    

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index'  %}">Home</a> - 
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>

</p>    
{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
<h1>Welcome</h1>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza:{{ pizza.name }}</p>

<p>Toppings</p>
<ul>
{% for topping in toppings %}
  <li>
    <p>{{ topping.name }}</p>
  </li>    
{% endfor %}  
</ul>

<a href="{% url 'pizzas:pizzas' %}">Back to Pizzas</a>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<ul>
  {% for pizza in pizzas %}
      <li><a href="{% url 'pizzas:pizza_toppings' pizza.id %}">{{ pizza.name }}</a></li>
  {% endfor %}
</ul>
  
{% endblock content %}  